# [project]
# name = "xacrodoc"
# version = "0.0.0"
# description = ""
# authors = ["Adam Heins <mail@adamheins.com>"]
# license = "MIT"
# readme = "README.md"
#
# dependencies = [
# python = ">=3.8,<3.12"
# xacro = "^1.14.16"
# rospkg = "^1.5.0"
# ]

[tool.black]
line-length = 80


# [build-system]
# requires = ["poetry-core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"
